# Generated by Django 2.1.3 on 2019-01-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190109_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='creator',
            new_name='title',
        ),
    ]
