# Generated by Django 2.1.3 on 2019-01-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='favorite',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(default='https://www.unesale.com/ProductImages/Large/notfound.png', max_length=500),
        ),
    ]
