# Generated by Django 2.1.3 on 2019-02-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_userprofile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='highscore',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.UserProfile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
