# Generated by Django 2.1.3 on 2019-02-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20190218_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
